import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` max-w-7xl px-4 md:px-0 mx-auto min-h-[1024px] antialiased `}
      >
        <Navbar />
        <div className="mt-44 ">{children}</div>
      </body>
    </html>
  );
}
